import Foundation

public struct DictionarySeedData {
    public static let initialDictionary: [String: WordDefinition] = [
        "CAT": WordDefinition(
            word: "CAT",
            phonetic: "/kæt/",
            partOfSpeech: "noun",
            definition: "A small domesticated carnivorous mammal with soft fur, a short snout, and retractile claws.",
            example: "The tabby cat curled up near the warm fireplace.",
            origin: "Old English catt, of Germanic origin; related to Dutch kat and German Katze.",
            synonyms: ["feline", "kitten", "kitty", "puss"]
        ),
        "ACT": WordDefinition(
            word: "ACT",
            phonetic: "/ækt/",
            partOfSpeech: "verb / noun",
            definition: "To take action; do something; or perform a role in a play or movie.",
            example: "They decided to act quickly before the deadline passed.",
            origin: "From Latin actus (a doing, driving) from agere (to do, drive).",
            synonyms: ["perform", "execute", "operate", "behave"]
        ),
        "SUN": WordDefinition(
            word: "SUN",
            phonetic: "/sʌn/",
            partOfSpeech: "noun",
            definition: "The star around which the earth orbits, providing light and heat.",
            example: "The morning sun cast a golden glow across the valley.",
            origin: "Old English sunne, from Proto-Germanic *sunnǭ.",
            synonyms: ["daystar", "sol", "sunlight", "sunbeam"]
        ),
        "SON": WordDefinition(
            word: "SON",
            phonetic: "/sʌn/",
            partOfSpeech: "noun",
            definition: "A boy or man in relation to his parents.",
            example: "He taught his son how to identify constellations at night.",
            origin: "Old English sunu, of Proto-Germanic origin.",
            synonyms: ["male offspring", "boy", "descendant"]
        ),
        "TAPE": WordDefinition(
            word: "TAPE",
            phonetic: "/teɪp/",
            partOfSpeech: "noun / verb",
            definition: "A narrow strip of material, typically with adhesive, used for fastening or recording.",
            example: "She secured the parcel with reinforced adhesive tape.",
            origin: "Old English tæppe (narrow strip of cloth).",
            synonyms: ["ribbon", "strip", "band", "adhesive"]
        ),
        "PART": WordDefinition(
            word: "PART",
            phonetic: "/pɑːrt/",
            partOfSpeech: "noun / verb",
            definition: "An amount or section which, with others, makes up the whole of something.",
            example: "Each part of the symphony harmonized in wondrous balance.",
            origin: "From Latin pars, particula (portion, piece).",
            synonyms: ["portion", "segment", "section", "fraction"]
        ),
        "PEAR": WordDefinition(
            word: "PEAR",
            phonetic: "/pɛər/",
            partOfSpeech: "noun",
            definition: "A sweet, juicy yellowish- or brownish-green fruit, typically narrow at the stalk and wider toward the base.",
            example: "The orchard produced crisp, honey-sweet pears every autumn.",
            origin: "From Latin pirum, through Old English peru.",
            synonyms: ["fruit", "pomaceous fruit"]
        ),
        "RATE": WordDefinition(
            word: "RATE",
            phonetic: "/reɪt/",
            partOfSpeech: "noun / verb",
            definition: "A measure, quantity, or frequency, typically one measured against some other quantity or measure.",
            example: "The pulse rate slowed to a calm, steady rhythm.",
            origin: "Medieval Latin rata (proportio).",
            synonyms: ["speed", "pace", "tempo", "ratio"]
        ),
        "FLAME": WordDefinition(
            word: "FLAME",
            phonetic: "/fleɪm/",
            partOfSpeech: "noun / verb",
            definition: "A hot glowing body of ignited gas that is generated by something on fire.",
            example: "A flickering flame illuminated the dark stone corridor.",
            origin: "Old French flambe, from Latin flamma.",
            synonyms: ["blaze", "fire", "flare", "glow"]
        ),
        "LEAF": WordDefinition(
            word: "LEAF",
            phonetic: "/liːf/",
            partOfSpeech: "noun",
            definition: "A flattened structure of a higher plant, typically green and blade-like, that is attached to a stem.",
            example: "A single autumn leaf drifted quietly onto the rippling brook.",
            origin: "Old English lēaf, of Germanic origin.",
            synonyms: ["foliage", "frond", "blade"]
        ),
        "FAME": WordDefinition(
            word: "FAME",
            phonetic: "/feɪm/",
            partOfSpeech: "noun",
            definition: "The state of being known or talked about by many people, especially on account of notable achievements.",
            example: "Her scientific breakthroughs brought international fame and respect.",
            origin: "From Latin fama (rumor, reputation).",
            synonyms: ["renown", "celebrity", "distinction", "prominence"]
        ),
        "MALE": WordDefinition(
            word: "MALE",
            phonetic: "/meɪl/",
            partOfSpeech: "adjective / noun",
            definition: "Of or denoting the sex that produces small, typically motile gametes.",
            example: "The male cardinal displayed striking crimson plumage.",
            origin: "Old French masle, from Latin masculus.",
            synonyms: ["masculine", "virile"]
        ),
        "BRAVE": WordDefinition(
            word: "BRAVE",
            phonetic: "/breɪv/",
            partOfSpeech: "adjective",
            definition: "Ready to face and endure danger or pain; showing courage.",
            example: "The brave explorer climbed through the icy canyon.",
            origin: "From Italian bravo, meaning bold or wild.",
            synonyms: ["courageous", "valiant", "fearless", "intrepid"]
        ),
        "BEAR": WordDefinition(
            word: "BEAR",
            phonetic: "/bɛər/",
            partOfSpeech: "noun / verb",
            definition: "A large, heavy mammal with thick fur and a very short tail, or to support and carry.",
            example: "The majestic brown bear waded across the salmon river.",
            origin: "Old English bera, of Germanic origin.",
            synonyms: ["endure", "sustain", "carry", "ursine"]
        ),
        "RAVE": WordDefinition(
            word: "RAVE",
            phonetic: "/reɪv/",
            partOfSpeech: "verb / noun",
            definition: "Talk wildly or incoherently, as if one were delirious or in a great passion.",
            example: "Critics rave about the author's luminous prose.",
            origin: "Old French raver, related to Middle Dutch raven.",
            synonyms: ["praise enthusiastically", "enthuse", "rhapsodize"]
        ),
        "VERB": WordDefinition(
            word: "VERB",
            phonetic: "/vɜːrb/",
            partOfSpeech: "noun",
            definition: "A word used to describe an action, state, or occurrence, and forming the main part of the predicate of a sentence.",
            example: "Every dynamic sentence hinges upon an active, expressive verb.",
            origin: "Latin verbum, meaning word.",
            synonyms: ["action word", "predicate"]
        ),
        "PLANET": WordDefinition(
            word: "PLANET",
            phonetic: "/ˈplæn.ɪt/",
            partOfSpeech: "noun",
            definition: "A celestial body moving in an elliptical orbit around a star.",
            example: "Earth is a vibrant planet teeming with oceans and life.",
            origin: "Greek planētēs (wanderer).",
            synonyms: ["world", "celestial body", "orb"]
        ),
        "PLANT": WordDefinition(
            word: "PLANT",
            phonetic: "/plænt/",
            partOfSpeech: "noun / verb",
            definition: "A living organism of the kind exemplified by trees, shrubs, herbs, grasses, ferns, and mosses.",
            example: "The botanical conservatory was filled with rare tropical plants.",
            origin: "Latin planta (sprout, shoot).",
            synonyms: ["flora", "vegetation", "herb"]
        ),
        "PLANE": WordDefinition(
            word: "PLANE",
            phonetic: "/pleɪn/",
            partOfSpeech: "noun / adjective",
            definition: "A flat surface on which a straight line joining any two points on it would wholly lie, or an aircraft.",
            example: "The architect drew the blueprint on a precise two-dimensional plane.",
            origin: "Latin planum (flat surface).",
            synonyms: ["flat surface", "aircraft", "level"]
        ),
        "LANE": WordDefinition(
            word: "LANE",
            phonetic: "/leɪn/",
            partOfSpeech: "noun",
            definition: "A narrow road, especially in a rural area, or a division of a road marked for traffic.",
            example: "Sunlight filtered down through the canopy of the country lane.",
            origin: "Old English lane, of Germanic origin.",
            synonyms: ["path", "alley", "passageway", "avenue"]
        ),
        "NEAT": WordDefinition(
            word: "NEAT",
            phonetic: "/niːt/",
            partOfSpeech: "adjective",
            definition: "Arranged in a tidy way; in good order.",
            example: "The calligrapher kept all her inks and quills in neat rows.",
            origin: "Old French net, from Latin nitidus (gleaming, elegant).",
            synonyms: ["tidy", "orderly", "spruce", "trim"]
        ),
        "WISDOM": WordDefinition(
            word: "WISDOM",
            phonetic: "/ˈwɪz.dəm/",
            partOfSpeech: "noun",
            definition: "The quality of having experience, knowledge, and good judgment; the soundness of an action or decision.",
            example: "True wisdom lies in knowing when to speak and when to listen.",
            origin: "Old English wīsdōm, from wīs (wise) + -dōm.",
            synonyms: ["sagacity", "intelligence", "insight", "discernment"]
        ),
        "WIND": WordDefinition(
            word: "WIND",
            phonetic: "/wɪnd/",
            partOfSpeech: "noun",
            definition: "The perceptible natural movement of the air, especially in the form of a current of air blowing from a particular direction.",
            example: "A gentle evening wind rustled the willow branches.",
            origin: "Old English wind, of Germanic origin.",
            synonyms: ["breeze", "gust", "gale", "draft"]
        ),
        "SWIM": WordDefinition(
            word: "SWIM",
            phonetic: "/swɪm/",
            partOfSpeech: "verb",
            definition: "Propel the body through water by using the limbs, or (in the case of a fish or other aquatic animal) by using fins, tail, or other bodily movement.",
            example: "Schools of iridescent fish swim across the coral reef.",
            origin: "Old English swimman, of Germanic origin.",
            synonyms: ["paddle", "float", "dive"]
        ),
        "MOD": WordDefinition(
            word: "MOD",
            phonetic: "/mɒd/",
            partOfSpeech: "noun / adjective",
            definition: "A modification made to something, or referring to a modern youth subculture.",
            example: "The developer released a graphical mod for the puzzle game.",
            origin: "Abbreviation of modification or modern.",
            synonyms: ["modification", "upgrade", "alteration"]
        ),
        "MASTER": WordDefinition(
            word: "MASTER",
            phonetic: "/ˈmæs.tər/",
            partOfSpeech: "noun / verb",
            definition: "A person with exceptional skill in a particular art or activity, or to acquire complete knowledge of something.",
            example: "With daily practice, she became a master of classical chess.",
            origin: "Latin magister (chief, teacher).",
            synonyms: ["expert", "virtuoso", "adept", "maestro"]
        ),
        "STREAM": WordDefinition(
            word: "STREAM",
            phonetic: "/striːm/",
            partOfSpeech: "noun / verb",
            definition: "A small, narrow river, or a continuous flow of liquid, air, or data.",
            example: "Clear mountain water flowed down the pebbled stream.",
            origin: "Old English strēam, of Germanic origin.",
            synonyms: ["brook", "creek", "rivulet", "current"]
        ),
        "SMART": WordDefinition(
            word: "SMART",
            phonetic: "/smɑːrt/",
            partOfSpeech: "adjective",
            definition: "Having or showing a quick-witted intelligence.",
            example: "Her smart deduction solved the riddle in seconds.",
            origin: "Old English smeart (painful, biting), later clever.",
            synonyms: ["clever", "intelligent", "sharp", "bright"]
        ),
        "TEAM": WordDefinition(
            word: "TEAM",
            phonetic: "/tiːm/",
            partOfSpeech: "noun",
            definition: "Two or more people working together in collaboration.",
            example: "The editorial team finalized the literary anthology.",
            origin: "Old English tēam (family, brood), of Germanic origin.",
            synonyms: ["squad", "group", "crew", "ensemble"]
        ),
        "LUMEN": WordDefinition(
            word: "LUMEN",
            phonetic: "/ˈluː.mən/",
            partOfSpeech: "noun",
            definition: "The SI unit of luminous flux, a measure of the total quantity of visible light emitted by a source per unit of time.",
            example: "The energy-efficient lantern emits over eight hundred lumens of light.",
            origin: "From Latin lumen, meaning light.",
            synonyms: ["luminous flux", "candlepower", "radiance"]
        ),
        "MENU": WordDefinition(
            word: "MENU",
            phonetic: "/ˈmɛn.juː/",
            partOfSpeech: "noun",
            definition: "A list of dishes available in a restaurant, or a list of options available to a computer user.",
            example: "The evening menu featured artisanal sourdough and garden soups.",
            origin: "French menu (detailed list), from Latin minutus (small).",
            synonyms: ["bill of fare", "listing", "catalog"]
        ),
        "MULE": WordDefinition(
            word: "MULE",
            phonetic: "/mjuːl/",
            partOfSpeech: "noun",
            definition: "The offspring of a donkey and a horse (strictly, a male donkey and a female horse), typically sterile and known for sure-footed stamina.",
            example: "The pack mule traversed the steep rocky incline with steady grace.",
            origin: "From Latin mulus.",
            synonyms: ["hybrid equine", "beast of burden"]
        ),
        "ELM": WordDefinition(
            word: "ELM",
            phonetic: "/ɛlm/",
            partOfSpeech: "noun",
            definition: "A tall deciduous tree with rough, doubly serrated leaves and winged fruits, native to north temperate regions.",
            example: "Centuries-old elms shaded the village green.",
            origin: "Old English elm, of Germanic origin.",
            synonyms: ["deciduous tree", "shade tree"]
        ),
        "LUMINOUS": WordDefinition(
            word: "LUMINOUS",
            phonetic: "/ˈluː.mɪ.nəs/",
            partOfSpeech: "adjective",
            definition: "Full of or shedding light; bright or shining, especially in the dark.",
            example: "Luminous stars painted the indigo night sky with brilliance.",
            origin: "From Latin luminosus, from lumen (light).",
            synonyms: ["radiant", "glowing", "lucid", "brilliant", "lustrous"]
        ),
        "VERDANT": WordDefinition(
            word: "VERDANT",
            phonetic: "/ˈvɜːr.dənt/",
            partOfSpeech: "adjective",
            definition: "Green with grass or other rich vegetation; fresh and flourish.",
            example: "The travelers gazed upon the verdant emerald valleys below.",
            origin: "From Old French verdoyant, from verdir (to grow green).",
            synonyms: ["lush", "green", "flourishing", "blooming"]
        ),
        "GROVE": WordDefinition(
            word: "GROVE",
            phonetic: "/ɡroʊv/",
            partOfSpeech: "noun",
            definition: "A small wood, orchard, or group of trees.",
            example: "An ancient olive grove surrounded the secluded monastery.",
            origin: "Old English grāf, of unknown origin.",
            synonyms: ["copse", "woodland", "orchard", "thicket"]
        ),
        "PASS": WordDefinition(
            word: "PASS",
            phonetic: "/pæs/",
            partOfSpeech: "verb / noun",
            definition: "To move past, go across, or proceed beyond a barrier or boundary.",
            example: "Gandalf raised his staff and declared: 'You shall not pass!'",
            origin: "From Old French passer, from Latin passus (a step).",
            synonyms: ["proceed", "traverse", "cross", "advance"]
        )
    ]
}
